architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

loom {
    accessWidenerPath = file("src/main/resources/stargate.accesswidener")
}

fabricApi {
    configureDataGeneration() {
        client = true
        modId = "stargate"
        outputDirectory = file("../common/src/main/generated")
    }
}

repositories {
    maven { url = "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    modImplementation(libs.fabric)
    modImplementation(libs.fabric.api)

    modImplementation(libs.geckolib.fabric)
    modImplementation(libs.cloth) { transitive false }

    modImplementation(libs.modmenu)
    modImplementation(libs.modonomicon.fabric) {
        exclude group: 'mezz.jei'
    }

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
}

tasks.withType(Jar).configureEach {
    from project(":common").sourceSets.main.output
}

tasks.withType(ProcessResources).configureEach {
    def modVersion = project.version
    inputs.property 'version', modVersion

    filesMatching('fabric.mod.json') {
        expand version: modVersion
    }
}

sourceSets {
    main.resources.srcDirs += [
            'src/main/generated',
    ]
}