plugins {
    alias(libs.plugins.loom) apply false
    alias(libs.plugins.architectury)
}

apply from: 'versioning.gradle'

version = getPublicVersion()

architectury {
    minecraft = libs.minecraft
}

allprojects {
    apply plugin: libs.plugins.architectury.get().pluginId

    group = rootProject.maven_group
    version = rootProject.version

    repositories {
        maven {
            name = "ParchmentMC"
            url = "https://maven.parchmentmc.org"

            content {
                includeGroup "org.parchmentmc.data"
            }
        }
    }
}

subprojects {
    apply plugin: libs.plugins.loom.get().pluginId

    base {
        archivesName = "$rootProject.name-$project.name"
    }

    loom {
        runs {
            named("client") {
                client()
                programArguments.add("--username=Dev")
            }
        }
    }

    repositories {
        maven {
            url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            content {
                includeGroup "software.bernie.geckolib"
            }
        }

        maven {
            name = "Modonomicon"
            url = "https://dl.cloudsmith.io/public/klikli-dev/mods/maven/"

            content {
                includeGroup "com.klikli_dev"
            }
        }
    }

    dependencies {
        minecraft(libs.minecraft)

        mappings loom.layered() {
            officialMojangMappings()
            parchment(libs.parchment)
        }

        constraints {
            add('implementation', libs.annotations.get()) {
                because 'Override transitive version'
            }
        }
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}
