# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true

# Mod properties
mod_version=0.0.0
maven_group=dev.amblelabs
enabled_platforms=fabric,neoforge
