# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod_version=0.0.0
maven_group=dev.amblelabs
archives_name=stargate
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
mappings_version=2024.11.17
# Dependencies
fabric_loader_version=0.19.1
neoforge_version=21.1.226

fabric_api_version=0.116.10
cloth_version=15.0.140
modmenu_version=11.0.3
geckolib_version=4.8.4
