plugins {
    alias(libs.plugins.json.processor)
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation(libs.fabric)

    modImplementation(libs.geckolib.common)
    modImplementation(libs.modonomicon.common)
}

processResources {
    filesMatching("**/*.json5") {
        name = name.dropRight(1) // rename to .json

        processJson {
            pipeline {
                flatten {
                    keyDelimiter = "."
                }
            }
        }
    }
}