plugins {
    id "coffee.cypher.json-processor" version "0.1.0"
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    modImplementation "software.bernie.geckolib:geckolib-common-$minecraft_version:$geckolib_version"

    modImplementation("com.klikli_dev:modonomicon-${minecraft_version}-common:${modonomicon_version}") { transitive false }
}

processResources {
    filesMatching("**/*.json5") {
        name = name.dropRight(1) // rename to .json

        processJson {
            pipeline {
                flatten {
                    keyDelimiter = "."
                }
            }
        }
    }
}