modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://codeberg.org/amblelabs/stargate/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "stargate"
version = "${version}"
displayName = "Stargate: Sojourner"
authors = "AmbleLabs"
description = '''

'''
#logoFile = ""

[[dependencies.stargate]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stargate]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "stargate.mixins.json"
