name: Publish to Amble Maven

on:
  workflow_dispatch:
  push:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Cache restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: src/main/generated
          key: datagen-${{ github.run_id }}
          restore-keys:
            datagen-

      - name: Build
        env:
          CI_MAVEN_PATH: ${{ runner.temp }}/maven
        run: |
          ./gradlew --configuration-cache runDatagen
          ./gradlew --configuration-cache publishMavenJavaPublicationToCiRepository

      - name: Publish
        uses: drtheodor/static-file-server-actions/upload@main
        with:
          repo: amblelabs/maven
          token: ${{ secrets.BOT_TOKEN }}
          path: ${{ runner.temp }}/maven

      - name: Cache save
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: src/main/generated
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}